export const PERMISSIONS = {
  DISPATCH_READ: "dispatch:read",
  DISPATCH_CREATE: "dispatch:create",
  DISPATCH_REVIEW: "dispatch:review",
  ORDERS_READ: "orders:read",
  ANOMALIES_READ: "anomalies:read",
  ANOMALIES_REPORT: "anomalies:report",
  AGENTS_READ: "agents:read",
  MEMORY_READ: "memory:read",
  MEMORY_MUTATE: "memory:mutate",
  RUNTIME_READ: "runtime:read",
  RUNTIME_OVERRIDE: "runtime:override",
  AUDIT_READ: "audit:read",
  MONITOR_READ: "monitor:read",
  SYSTEM_ADMIN: "system:admin",
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];
export type Role = "EMPLOYEE" | "DISPATCHER" | "SUPERVISOR" | "OPERATOR" | "AUDITOR" | "ADMIN";

const dispatcher: Permission[] = [
  PERMISSIONS.DISPATCH_READ,
  PERMISSIONS.DISPATCH_CREATE,
  PERMISSIONS.ORDERS_READ,
  PERMISSIONS.ANOMALIES_READ,
  PERMISSIONS.AGENTS_READ,
  PERMISSIONS.MEMORY_READ,
];

export const ROLE_PERMISSION_MATRIX: Record<Role, readonly Permission[]> = {
  EMPLOYEE: [PERMISSIONS.DISPATCH_READ, PERMISSIONS.ANOMALIES_REPORT],
  DISPATCHER: dispatcher,
  SUPERVISOR: [...dispatcher, PERMISSIONS.DISPATCH_REVIEW, PERMISSIONS.MEMORY_MUTATE, PERMISSIONS.RUNTIME_READ, PERMISSIONS.RUNTIME_OVERRIDE, PERMISSIONS.AUDIT_READ, PERMISSIONS.MONITOR_READ],
  OPERATOR: [PERMISSIONS.AGENTS_READ, PERMISSIONS.RUNTIME_READ, PERMISSIONS.AUDIT_READ, PERMISSIONS.MONITOR_READ],
  AUDITOR: [PERMISSIONS.MEMORY_READ, PERMISSIONS.RUNTIME_READ, PERMISSIONS.AUDIT_READ, PERMISSIONS.MONITOR_READ],
  ADMIN: Object.values(PERMISSIONS),
};

export function permissionsForRole(role: Role): readonly Permission[] {
  return ROLE_PERMISSION_MATRIX[role];
}
