from datetime import datetime
from typing import Protocol

from app.vehicle_operations.models import BreakdownCaseRequest, OperationCaseSnapshot


class VehicleOperationsRepository(Protocol):
    def vehicle_node(self, vehicle_id: str) -> str: ...
    def update_replacement_route(self, task_id: str, edge_ids: tuple[str, ...]) -> OperationCaseSnapshot: ...
    def create_breakdown_case(self, request: BreakdownCaseRequest) -> OperationCaseSnapshot: ...
    def get_case(self, task_id: str) -> OperationCaseSnapshot | None: ...
    def advance_one_due_rescue(self, now: datetime) -> OperationCaseSnapshot | None: ...
    def advance_one_due_maintenance(self, now: datetime) -> OperationCaseSnapshot | None: ...
    def retry_rescue(self, mission_no: str, now: datetime) -> OperationCaseSnapshot: ...
    def record_inspection(self, order_no: str, *, passed: bool, decided_at: datetime, decided_by: str) -> OperationCaseSnapshot: ...


class Clock(Protocol):
    def now(self) -> datetime: ...
